dist: trusty
language: ruby
cache: bundler
sudo: false
services:
- redis-server
rvm:
- 2.4.2
before_script:
- bundle exec rake db:create
script:
- bundle exec rubocop
- xvfb-run -a bundle exec rake ci
notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
before_install:
- openssl aes-256-cbc -K $encrypted_fc64690fc6b2_key -iv $encrypted_fc64690fc6b2_iv
  -in cypripedium-cd-deploy.enc -out ./cypripedium-cd-deploy -d
after_success:
  - |
    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
      bundle exec cap dce_cd deploy
    fi
