dist: trusty
language: ruby
cache: bundler
sudo: required
addons:
  chrome: stable
services:
- redis-server
- postgresql
rvm:
- 2.5.3
before_script:
- bundle exec rake db:create
script:
- bundle exec rubocop
- xvfb-run -a bundle exec rake ci
notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
before_install:
- openssl aes-256-cbc -K $encrypted_fc64690fc6b2_key -iv $encrypted_fc64690fc6b2_iv
  -in cypripedium-cd-deploy.enc -out ./cypripedium-cd-deploy -d
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

after_success:
  - |
    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
      bundle exec cap dce_cd deploy
    fi
