terms:
  - id: 'Federal Reserve Bank of Minneapolis. Research Division.'
    term: 'Federal Reserve Bank of Minneapolis. Research Division.'
    active: true
  - id: 'Federal Reserve Bank of Minneapolis. Community Development.'
    term: 'Federal Reserve Bank of Minneapolis. Community Development.'
    active: true
