terms:
  - id: 'Working paper (Federal Reserve Bank of Minneapolis. Research Department)'
    term: 'Working paper (Federal Reserve Bank of Minneapolis. Research Department)'
    active: true
  - id: 'Staff report (Federal Reserve Bank of Minneapolis. Research Department)'
    term: 'Staff report (Federal Reserve Bank of Minneapolis. Research Department)'
    active: true
  - id: 'Quarterly review (Federal Reserve Bank of Minneapolis. Research Department)'
    term: 'Quarterly review (Federal Reserve Bank of Minneapolis. Research Department)'
    active: true
  - id: 'Discussion paper (Federal Reserve Bank of Minneapolis. Institute for Empirical Macroeconomics)'
    term: 'Discussion paper (Federal Reserve Bank of Minneapolis. Institute for Empirical Macroeconomics)'
    active: true
  - id: 'Monthly review (Federal Reserve Bank of Minneapolis. Research Department)'
    term: 'Monthly review (Federal Reserve Bank of Minneapolis. Research Department)'
    active: true
  - id: 'Ninth District conditions (Federal Reserve Bank of Minneapolis. Research Department)'
    term: 'Ninth District conditions (Federal Reserve Bank of Minneapolis. Research Department)'
    active: true
  - id: 'Ninth District quarterly (Federal Reserve Bank of Minneapolis. Research Department)'
    term: 'Ninth District quarterly (Federal Reserve Bank of Minneapolis. Research Department)'
  - id: 'Institute working paper (Federal Reserve Bank of Minneapolis. Opportunity and Inclusive Growth Institute)'
    term: 'Institute working paper (Federal Reserve Bank of Minneapolis. Opportunity and Inclusive Growth Institute)'
