schema_org:
  alpha_creator:
    property: creator
    type: "http://schema.org/Person"
    value: name
  abstract:
    property: abstract
  identifier:
    property: identifier
  description:
    property: description
